target("llaisys-device-nvidia")
    set_kind("static")
    add_rules("cuda")
    set_languages("cxx17")
    set_warnings("all")
    add_cugencodes("native")
    add_cuflags("-Xcompiler=-fPIC", {force = true})
    add_culdflags("-Xcompiler=-fPIC", {force = true})
    add_values("cuda.build.devlink", true)
    add_files("../src/device/nvidia/*.cu")

    on_install(function (target) end)
target_end()
